name = "CraftNectar"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c90b577707a4a838cff1279f7dd86335a9437e77da9bc1c7b38c3b17a10a0d7"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
