name = "CraftNectar"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f07ab2c5b204c227b16a653571808be801ee3570f4710d3a6399844d6d4800b6"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
